# Generated by Django 3.1.7 on 2021-05-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basiclogin', '0003_rfidtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidtag',
            name='rfid',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
