# Generated by Django 3.1.7 on 2021-05-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basiclogin', '0004_rfidtag_rfid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfidtag',
            name='ddate',
            field=models.DateField(),
        ),
    ]
