@username = restuie
@password = restuie555
POST http://127.0.0.1:8000/my_view HTTP/1.1
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

{
    "username": "restuie",
}

###
GET http://127.0.0.1:8000/snippets/ HTTP/1.1


###
POST http://127.0.0.1:8000/my_view HTTP/1.1
Content-Type: application/json

{
    "username": "restuie",
}